assistant_name: Megatron
briefing_evening_time: '21:00'
briefing_morning_time: 08:00
hardware_monitor_interval: 30
lock_mode: false
log_level: INFO
ollama_url: http://localhost:11434
gemini_api_key: 'YOUR_API_KEY_HERE
os: ''
password_hash: $2b$12$4LnMmP6YAykWfhhDLn437u8hUY9jgYXEyLhhHhunW/61h1odhotJa
preferred_language: en
proactive_enabled: false
push_to_talk: true
setup_complete: true
sync_enabled: false
sync_server_url: http://localhost:8000
theme: dark
transparency: 0.95
user_name: User
wakeword_enabled: false
